apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpledeploy
spec:
  selector:
    matchLabels:
      app: simpledeploy
  replicas: 1
  template:
    metadata:
      labels:
        app: simpledeploy
    spec:
      containers:
      - name: simpledeploy
        image: docker.io/fajarnrs/simpleservice:v1
        ports:
        - containerPort: 9876

---
apiVersion: v1
kind: Service
metadata:
  name: simpleservice
  labels:
    run: simpleservice
spec:
  ports:
  - name: simpledeploy
    port: 9876
    targetPort: 9876
  selector:
    app: simpledeploy
  type: ClusterIP
